-- Create keep-alive table to prevent Supabase inactivity pausing
-- Based on: https://github.com/Sevrene/supabase-inactive-fix-github-action

CREATE TABLE IF NOT EXISTS "keep-alive" (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY,
  name text NULL DEFAULT ''::text,
  random uuid NULL DEFAULT gen_random_uuid(),
  created_at timestamptz DEFAULT NOW(),
  CONSTRAINT "keep-alive_pkey" PRIMARY KEY (id)
);

-- Insert initial placeholder data
INSERT INTO "keep-alive"(name)
VALUES 
  ('placeholder'),
  ('initial-entry')
ON CONFLICT DO NOTHING;

-- Add helpful comment
COMMENT ON TABLE "keep-alive" IS 'Table used by GitHub Actions to keep Supabase project active by periodically inserting and cleaning up entries';
COMMENT ON COLUMN "keep-alive".name IS 'Descriptive name for the keep-alive entry';
COMMENT ON COLUMN "keep-alive".random IS 'Random UUID generated for each entry';
COMMENT ON COLUMN "keep-alive".created_at IS 'Timestamp when the entry was created'; 