name: Keep Supabase Awake

on:
  schedule:
    # Run every 14 minutes (just under the 15-minute sleep threshold)
    - cron: '*/14 * * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  keep-awake:
    runs-on: ubuntu-latest
    
    steps:
      - name: Ping Supabase Project
        run: |
          # Ping the Supabase project URL to keep it awake
          curl -f -s "${{ secrets.SUPABASE_URL }}/rest/v1/" \
            -H "apikey: ${{ secrets.SUPABASE_ANON_KEY }}" \
            -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" || echo "Ping failed but continuing..."
          
          echo "✅ Pinged Supabase project at $(date)"

      - name: Ping Application (if deployed)
        run: |
          # Also ping your deployed application if you have one
          if [ -n "${{ secrets.APP_URL }}" ]; then
            curl -f -s "${{ secrets.APP_URL }}" || echo "App ping failed but continuing..."
            echo "✅ Pinged application at $(date)"
          else
            echo "ℹ️ No APP_URL configured, skipping app ping"
          fi

      - name: Health Check Log
        run: |
          echo "🏥 Health check completed at $(date)"
          echo "📊 Supabase URL: ${{ secrets.SUPABASE_URL }}"
          echo "🚀 Keeping your project alive and healthy!" 